### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by gsacre** [linuxserver/docker-nginx#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Latest nginx docker image (image ID: e70f8c94d769) starts using docker-compose.

## Current Behavior
When starting the image with docker-copose, the container never runs (it directly exits, only visible using `docker ps -a`).

## Steps to Reproduce

1. Create a docker-compose file with the below configuration
2. run `docker-compose -f <your-docker-compose-file> up -d`

I don't know if this would be relevant but I created a Swarm with 2 nodes and running docker-compose on one of the nodes before deploying the service. The service has never been deployed as nginx is currently failing.

## Environment
**OS:** Ubuntu 18.04 server
**CPU architecture:** x86_64
**How docker service was installed:** Official documentation from docker website
**Docker version:** Docker version 19.03.5, build 633a0ea838
**docker-compose version:** docker-compose version 1.25.0, build 0a186604

## Command used to create docker container

`docker-compose -f test.yml up -d`

`test.yml` docker-compose file:
```    
version: '3.7'
networks:
    cluster:
        driver: bridge    
services:
    nginx:
        image: linuxserver/nginx
        entrypoint: nginx
        container_name: nginx
        ports:
            - 80:80
        networks:
            cluster:
                aliases:
                    - nginx
```
## Docker logs

```
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
```
