### ISSUE TITLE
Manually adding geoip2 crashes docker

### ISSUE THREAD

**Issue by juan11perez** [linuxserver/docker-nginx#62]
Followed instruction "Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb"

After manually adding the db in the instructed directory, the docker crashes. No logs created

## Environment
Unraid

## Command used to create docker container
Sample docker-compose

**Comment by aptalca** [comment]
We're gonna need more info than `docker crashes`

**Comment by juan11perez** [comment]
thank you. It just doesnt start. Without the db it starts. If I load the db it doesnt start.
I also run a "clean" install. i.e didnt add any configuration files. All I did was add the db and the same persisted. 
The docker doesnt start.

**Comment by aptalca** [comment]
I don't follow. Describe `load the db` and `doesn't start`. What exactly are you doing? You just need to save a file inside the config folder. That has nothing to do with the container starting or not

**Comment by juan11perez** [comment]
I initiate the docker following the docker compose sample:

```
  nginx:
    container_name: nginx
    image: linuxserver/nginx
    restart: unless-stopped
    network_mode: bridge
    volumes:
    - /mnt/cache/appdata/nginx:/config
    environment:
    - TZ=Asia/Dubai
    - PGID=100
    - PUID=99
    ports:
    - 180:80
    - 1443:443
    labels:
    - "com.centurylinklabs.watchtower.enable=true" 
```

it initiates without any errors. 
in the log i get the message regarding "Starting 2019/12/30, GeoIP2 .."
I go into maxmind, signup, etc and download GeoLite2-City.mmdb
stop the container
I then add the file into /config/geoip2db/
restart the container. 
it doesnt restart. it terminates with the error "exit kill........"
